<a href="https://colab.research.google.com/github/fannyfagame-spec/NoteBook-Jupiter/blob/main/%5BJupyter_Notebooks_Youth%5D_NumPy_Arrays%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size="+3">Module 33 - NumPy arrays</font>

In this notebook, we are going to discuss about
- Create an array (1-D,2-D,3-D)
- NumPy Array attributes -shape, len, ndim,dtype,astype,size,axis
- Indexing and Slicing of Array
- Array Manipulation- resize, reshape, append,delete,insert

- Let us understand the common notation of NumPy arrays throughout this notebook
-1-D array: notation used is arr1D
-2-D array: notation used is arr2D
-3-D array: notation used is arr3D

## Create an NumPy array

In [1]:
# Import a numpy library
import numpy as np

In [2]:
#for adding audio,image and YouTube video within Jupyter Notebook
from IPython.display import Audio,Image,YouTubeVideo

### 1D array

In [3]:
# Import a numpy library
import numpy as np
#create 1-D numpy array
arr1D = np.array([5, 8, 12])
print(arr1D)

[ 5  8 12]


### 2D array

In [4]:
# create a 2D array
arr2D = np.array([[23,45,67],[78,65,92]])
print(arr2D)

[[23 45 67]
 [78 65 92]]


### 3D array

In [5]:
# create a 3D array
arr3D=np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Create NumPy Arrays </p>**

In [6]:
# Exercise create 1-D array

In [7]:
arr1D = np.array([1, 2, 3])
print(arr1D)

[1 2 3]


In [8]:
# Exercise create 2-D array

In [9]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [10]:
# Exercise create 3-D array

In [11]:
arr3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## NumPy Array Attributes

### attribute-shape

In [12]:
# 1-D array
arr1D

array([1, 2, 3])

In [13]:
arr1Dshape=np.shape(arr1D)
arr1Dshape

(3,)

In [14]:
# 2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
arr2Dshape=np.shape(arr2D)
arr2Dshape

(2, 3)

In [16]:
# 3-D array
arr3D=np.array([[[2,17], [45, 78]], [[88, 92], [60, 76]],[[76,33],[20,18]]])
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [17]:
arr3Dshape=np.shape(arr3D)
arr3Dshape

(3, 2, 2)

### attribute-length

In [18]:
# len-Size of the first dimension of the NumPy array
#1-D array
arr1D

array([1, 2, 3])

In [19]:
# find the length of the array
print(len(arr1D))

3


In [20]:
#2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
# find the length of the array
print(len(arr2D))

2


In [22]:
# 3-D array
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [23]:
# find the length of the array
print(len(arr3D))

3


### attribute-ndimensions

In [24]:
# ndim
#1-D array
arr1D

array([1, 2, 3])

In [25]:
# apply ndim
print(arr1D.ndim)

1


In [26]:
# ndim-Number of dimensions of the NumPy array
#2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
#apply ndim
print(arr2D.ndim)

2


In [28]:
#3-D array
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [29]:
# apply ndim
print(arr3D.ndim)

3


### attribute-data type

In [30]:
# data type
# 1-D array
arr1D

array([1, 2, 3])

In [31]:
#data type
print(arr1D.dtype)

int64


In [32]:
## 1-D array data type
arr1Dnew=np.array(['Tom','Nick'])
arr1Dnew

array(['Tom', 'Nick'], dtype='<U4')

In [33]:
#data type
print(arr1Dnew.dtype)

<U4


In [34]:
# 2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
# data type
print(arr2D.dtype)

int64


In [36]:
## 2-D array data type
arr2Dnew = np.array([[1+2j,1+3j],[5+6j,3+8j]])
arr2Dnew

array([[1.+2.j, 1.+3.j],
       [5.+6.j, 3.+8.j]])

In [37]:
# 2D array
print(arr2Dnew.dtype)

complex128


In [38]:
# 3-D array
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [39]:
# data type
print(arr3D.dtype)

int64


### attribute-astype

In [40]:
# astype- changes the data type from one type to another data type
#In order to change the dtype of the given array object, we will use numpy.astype() function.
#The function takes an argument which is the target data type.
#The function supports all the generic types and built-in types of data.

-- Example: Given a numpy array whose underlying data is of 'int32' type. Change the dtype of the given object to 'float64'.

In [41]:
# Create a numpy array
Astypearr1D = np.array([10, 20, 30, 40, 50])
# Print the array
print(Astypearr1D)
print(Astypearr1D.dtype)

[10 20 30 40 50]
int64


In [42]:
# change the dtype to 'float64'
Astypearr1D= Astypearr1D.astype('float64')
print(Astypearr1D)
print(Astypearr1D.dtype)

[10. 20. 30. 40. 50.]
float64


### attribute-size

In [43]:
# size of the array
# 1-D array
arr1D

array([1, 2, 3])

In [44]:
# size of array
print(arr1D.size)

3


In [45]:
# 2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
#size of array
print(arr2D.size)

6


In [47]:
# 3-D array
arr3D

array([[[ 2, 17],
        [45, 78]],

       [[88, 92],
        [60, 76]],

       [[76, 33],
        [20, 18]]])

In [48]:
#size of array
print(arr3D.size)

12


**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: NumPy attributes </p>**

In [49]:
## 1.Write a NumPy program to create a 2-dimensional array of size 2 x 3 .Print the shape, type and data type of the array.

In [50]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(type(arr))
print(arr.dtype)

(2, 3)
<class 'numpy.ndarray'>
int64


In [51]:
## 2.Given a numpy array ([20,30,40]) whose underlying data is of 'int32' type.
## Change the dtype of the given object to 'complex128'.

In [52]:
arr = np.array([20, 30, 40])
arr = arr.astype('complex128')
print(arr)
print(arr.dtype)

[20.+0.j 30.+0.j 40.+0.j]
complex128


### attribute-axis

![axis%20image.jpeg](attachment:axis%20image.jpeg)

 ## Indexing and Slicing of an array

In [53]:
# 1-D array
arr1D

array([1, 2, 3])

In [54]:
## accessing the elements
arr1D[0]

np.int64(1)

In [55]:
## accessing the elements
arr1D[2]

np.int64(3)

In [56]:
# 2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
## accessing the elements
arr2D[0,0]

np.int64(1)

In [58]:
arr2D[0,1]

np.int64(2)

In [59]:
arr2D[0,2]

np.int64(3)

In [60]:
arr2D[1,0]

np.int64(4)

In [61]:
arr2D[1,1]

np.int64(5)

In [62]:
arr2D[1,2]

np.int64(6)

In [63]:
## Let's apply slicing to 1-D array
arrSlice=np.array([5, 8, 12, 19, 14, 13])
arrSlice

array([ 5,  8, 12, 19, 14, 13])

In [64]:
arrSlice[2:5]

array([12, 19, 14])

In [65]:
arrSlice[:4]

array([ 5,  8, 12, 19])

In [66]:
arrSlice[4:]

array([14, 13])

In [67]:
## Let's apply slicing to a 2-D array
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
arr2D[:1,:2]

array([[1, 2]])

In [69]:
arr2D[1:2]

array([[4, 5, 6]])

In [70]:
arr2D[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: NumPy indexing and slicing </p>**

In [71]:
## 1. Get third and fourth elements from the following array
##([1, 2, 3, 4])

In [72]:
arr = np.array([1, 2, 3, 4])
print(arr[2:4])

[3 4]


In [73]:
## 2.Access the element on the first row, second column from the following 2D array
## ([[1,2,3,4,5], [6,7,8,9,10]])

In [74]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

2


In [75]:
## 3.Slice elements from index 1 to index 5 from the following array:
# arr=([1, 2, 3, 4, 5, 6, 7])

In [76]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [77]:
## 4.Slice elements from index 4 to the end of the array:
# arr=([31, 21, 53, 14, 85, 16, 27])

In [78]:
arr = np.array([31, 21, 53, 14, 85, 16, 27])
print(arr[4:])

[85 16 27]


In [79]:
## 5. Slice elements from the beginning to index 4 (not included):
# arr=([31, 21, 53, 14, 85, 16, 27])

In [80]:
arr = np.array([31, 21, 53, 14, 85, 16, 27])
print(arr[:4])

[31 21 53 14]


## Array Manipulation

### resize

In [81]:
# resize() of the array:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
# lets use resize of array
arr2D.resize(1,6)
arr2D

array([[1, 2, 3, 4, 5, 6]])

In [83]:
arr2D.resize(6,1)
arr2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [84]:
# Array
arr2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### reshape

In [85]:
# lets use reshape of array
arr2D.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
arr2D.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [87]:
arr2D.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [88]:
arr2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [89]:
arr2D.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

### Append data in an NumPy array

In [90]:
# Let's create a new array and try to append data to the array
AppendArray= np.array([[1,2,3],[4,5,6]])
AppendArray

array([[1, 2, 3],
       [4, 5, 6]])

In [91]:
print(np.append(AppendArray,[7,8,9]))

[1 2 3 4 5 6 7 8 9]


In [92]:
print (np.append(AppendArray, [[7,8,9]],axis = 0))    # elements along x-axis

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [93]:
print (np.append(AppendArray, [[5,5,5],[7,8,9]],axis = 1)) # elements along y-axis

[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


### Delete data from a NumPy array

In [94]:
# Let's create a new array and try to delete data
Deletearr2D = np.array([[23,45,67],[78,65,92]])
print(Deletearr2D)

[[23 45 67]
 [78 65 92]]


In [95]:
object=[0,1]
Deletearr2D = np.delete(Deletearr2D,object)
Deletearr2D

array([67, 78, 65, 92])

### Insert data into an NumPy array

In [96]:
# Let's create a new array and try to insert data
Insertarr2D = np.array([[23,45,67],[78,65,92]])
print(Insertarr2D)

[[23 45 67]
 [78 65 92]]


In [97]:
Insertarr2D = np.insert(Insertarr2D, 1, 9, axis = 1)
Insertarr2D

array([[23,  9, 45, 67],
       [78,  9, 65, 92]])

In [98]:
Insertarr2D = np.insert(Insertarr2D, [1,2], 9, axis = 1)
Insertarr2D

array([[23,  9,  9,  9, 45, 67],
       [78,  9,  9,  9, 65, 92]])

In [99]:
arr2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Array Manipulations </p>**

In [100]:
## 1. Convert the following 1-D array with 12 elements into a 2-D array.
## ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [101]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(arr.reshape(3, 4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
## 2.Append elements ([7,8,9]) along axis=0 for the given array=([[1,2,3],[4,5,6]])

In [103]:
arr = np.array([[1,2,3],[4,5,6]])
print(np.append(arr, [[7,8,9]], axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [104]:
## 3. Insert elements in an array ([11,13]) along axis=1 in the array ([[1,2],[3,4],[5,6]])

In [109]:

arr = np.array([[1,2],[3,4],[5,6]])
print(np.insert(arr, 1, [11,13], axis=0))

[[ 1  2]
 [11 13]
 [ 3  4]
 [ 5  6]]
