<a href="https://colab.research.google.com/github/fannyfagame-spec/NoteBook-Jupiter/blob/main/%5BJupyter_Notebooks_Youth%5D_Basic_Data_Operations_in_NumPy_arrays%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<font size="+3">Module 33 - Basic Data Operations in NumPy arrays</font>

In this notebook, we are going to discuss about:
- Arithmetic operations in NumPy
- Matrix operations in NumPy
- Statistical Operations in NumPy

## Section 1: Arithmetic operations in NumPy
### NumPy add function and operator

In [1]:
# import numpy library
import numpy as np

In [2]:
# Create two arrays of same size and dimensions
# NumPy Add function
AddarrA=np.array([10,20,30,40])
AddarrB=np.array([1,2,3,4])
np.add(AddarrA,AddarrB)

array([11, 22, 33, 44])

In [3]:
# NumPy add operator
AddarrA,AddarrB

(array([10, 20, 30, 40]), array([1, 2, 3, 4]))

In [4]:
# add arrays using '+' operator
AddarrA+AddarrB

array([11, 22, 33, 44])

### NumPy subtract function and operator

In [5]:
# Create two arrays of same size and structure
# NumPy Subtract function
SubtractarrA=np.array([25,15,35,45])
SubtractarrB=np.array([10,6,11,18])
np.subtract(SubtractarrA,SubtractarrB)

array([15,  9, 24, 27])

In [6]:
# NumPy subtract operator
SubtractarrA,SubtractarrB

(array([25, 15, 35, 45]), array([10,  6, 11, 18]))

In [7]:
# subtract  arrays using '-' operator
SubtractarrA-SubtractarrB

array([15,  9, 24, 27])

### NumPy multiply function and operator

In [8]:
# Create two arrays of same size and structure
# NumPy Mutiply function
MultiplyarrA=np.array([3,5,7,9,11])
MultiplyarrB=np.array([2,4,6,8,10])
np.multiply(MultiplyarrA,MultiplyarrB)

array([  6,  20,  42,  72, 110])

In [9]:
# NumPy multiply operator
MultiplyarrA,MultiplyarrB

(array([ 3,  5,  7,  9, 11]), array([ 2,  4,  6,  8, 10]))

In [10]:
# multiply two arrays using '*' operator
MultiplyarrA*MultiplyarrB

array([  6,  20,  42,  72, 110])

### NumPy divide function and operator

In [11]:
# Create two arrays of same size and structure
# NumPy Divide function
DividearrA=np.array([10,15,27,39,51])
DividearrB=np.array([2,3,9,13,16])
np.divide(DividearrA,DividearrB)

array([5.    , 5.    , 3.    , 3.    , 3.1875])

In [12]:
# NumPy divide operator
DividearrA,DividearrB

(array([10, 15, 27, 39, 51]), array([ 2,  3,  9, 13, 16]))

In [13]:
# divide arrays using '/' operator
DividearrA/DividearrB

array([5.    , 5.    , 3.    , 3.    , 3.1875])

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Arithmetic Operations </p>**

In [14]:
## 1. Using add function add two arrays A=([[2, -7, 5], [-6, 2, 0]]); B=([[5, 8, -5], [3, 6, 9]])

In [15]:
A = np.array([[2, -7, 5], [-6, 2, 0]])
B = np.array([[5, 8, -5], [3, 6, 9]])
np.add(A, B)

array([[ 7,  1,  0],
       [-3,  8,  9]])

In [16]:
## 2. Using multiply function add two arrays A = ([[7, -7], [-6, 2]]);B = ([[2, 7], [5, 9]])

In [17]:
A = np.array([[7, -7], [-6, 2]])
B = np.array([[2, 7], [5, 9]])
np.multiply(A, B)

array([[ 14, -49],
       [-30,  18]])

## Section 2: Matrix operations in NumPy
### Inner Product

In [18]:
# Vectors as 1D numpy arrays
# Create two vectors
InnerarrA = np.array([1, 2, 3])
InnerarrB = np.array([4, 5, 6])
print(InnerarrA,InnerarrB)

[1 2 3] [4 5 6]


In [19]:
# Calculate inner product
np.inner(InnerarrA,InnerarrB)

np.int64(32)

In [20]:
# Calculate the dot product
np.dot(InnerarrA,InnerarrB)

np.int64(32)

### Dot Product

In [21]:
# Matrices as ndarray objects
DotarrA = np.array([[1, 2], [3, 4]])
DotarrB = np.array([[5, 6, 7], [8, 9, 10]])
print(DotarrA)

[[1 2]
 [3 4]]


In [22]:
print(DotarrB)

[[ 5  6  7]
 [ 8  9 10]]


In [23]:
# apply dot product
np.dot(DotarrA,DotarrB)

array([[21, 24, 27],
       [47, 54, 61]])

### Transpose of a matrix

In [24]:
#Create an array
Newarr = np.array([[1, 2], [3, 4], [5, 6]])
Newarr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
# Apply transpose of a matrix
np.transpose(Newarr)

array([[1, 3, 5],
       [2, 4, 6]])

**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Matrix Operations </p>**

In [26]:
## 1. Find the inner product of two arrays: a = ([[1,2], [3,4]]) ,b = ([[11, 12], [13, 14]])

In [27]:
a = np.array([[1,2], [3,4]])
b = np.array([[11, 12], [13, 14]])
np.inner(a, b)

array([[35, 41],
       [81, 95]])

In [28]:
## 2. Find the transpose of array ([[0, 2],[1, 3]])

In [29]:
arr = np.array([[0, 2],[1, 3]])
np.transpose(arr)

array([[0, 1],
       [2, 3]])

## Section 3: Statistical Operations in NumPy

### mean

In [30]:
# Create an array
ArrMean = np.array([5,6,7])
ArrMean

array([5, 6, 7])

In [31]:
# mean
print(np.mean(ArrMean))

6.0


### median

In [32]:
# create array
ArrMedian=np.array([5,6,7])
ArrMedian

array([5, 6, 7])

In [33]:
# median
print(np.median(ArrMedian))

6.0


### Standard Deviation

In [34]:
# create array
ArrStdDev=np.array([5,6,7])
ArrStdDev

array([5, 6, 7])

In [35]:
# standard deviation
print(np.std(ArrStdDev))

0.816496580927726


**<p style="font-family: Arial; font-size:1.4em;color:blue;">Exercise: Statistical Operations </p>**

In [36]:
## Find the mean, median, and standard deviation of the array ([10,56,23,97])

In [37]:
arr = np.array([10, 56, 23, 97])
print(np.mean(arr))

46.5


In [38]:
print(np.median(arr))

39.5


In [39]:
print(np.std(arr))

33.63406011768428
